name: Build Docker Image

on:
  push:
    branches: [ main , dev ]
  release:
    types: [ published ]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Tag Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: penguin-statistics/backend-next
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: '${{ steps.get_version.outputs.VERSION }}'
